---
plugin: amazon.aws.aws_ec2
aws_access_key_id: "{{ 'vault_aws_access_key' }}"
aws_secret_access_key: "{{ 'vault_aws_secret_key' }}"
regions:
  - ap-southeast-1
keyed_groups:
  - key: placement.region
    prefix: aws_region
  - key: tags.Env
    prefix: env
  - key: tags.Project
    prefix: project
hostnames:
  - public-ip-address
  - private-ip-address
compose:
  ansible_host: public_ip_address
host_options:
  ansible_user: ubuntu
