---
plugin: amazon.aws.aws_ec2
aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
aws_security_token: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default(omit) }}"
regions:
  - "{{ aws_region }}"
keyed_groups:
  - key: placement.region
    prefix: aws_region
  - key: tags.Env
    prefix: env
  - key: tags.Project
    prefix: project
hostnames:
  - private-ip-address
host_options:
  ansible_user: ec2-user
